name: Makefile CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: git submodule update --init --recursive
      
    - name: Compile
      run: make
